### ISSUE TITLE
Main Page: 특정 계정(신규 회원가입한 회원으로 추정) Login 시 500에러

### ISSUE THREAD

**Issue by pongpongie** [TeamMoHead/ModuGisang#117]
## #️⃣ 발생한 곳

auth 페이지에서 로그인 후 main페이지에서 발생

## 🔎 발견한 이슈

`userId`가 `13`인 유저가 로그인 후 main페이지로 접속하면 error code 500과 함께 메인 페이지 로드 불가
새로 회원가입 한 유저에게 발생한 문제로 보입니다.

프론트의 경우 `authServices`의 `getUserInfo` api를 호출하는 도중 발생한 문제입니다.

## 📝 재현 스텝

1. auth 페이지에서 id : `arevolvera@gmail.com`, pw : `1234`로 로그인
2. 메인 페이지 불러오는 중 error 발생

## 📌 발생 환경
- 모바일, pc 공통

## 🔗 예상 영향
- 신규 회원 가입 시 오류 발생 가능

### 스크린샷 (선택)
<img width="939" alt="image" src="https://github.com/TeamMoHead/ModuGisang/assets/98201095/b6437ffb-0529-4711-92da-8237b23f76a4">

## 💬 그 외 참고 사항(선택)
이슈 처음 올려보는 겸 해서 올려봅니다.
형식에 맞지 않거나 더 좋은 issue 작성법이 있다면 공유해주세요!

수요일에 한 번 말씀드렸었던 오류인 것 같은데, @won0845 님이 해결 했었던 것으로 기억합니다.

**Comment by ifindary** [comment]
매우 깔끔한 이슈 등록입니다 👍
