### ISSUE TITLE
Result UI: 결과 화면에서 글자 넘치는 현상

### ISSUE THREAD

**Issue by ifindary** [TeamMoHead/ModuGisang#118]
## #️⃣ 발생한 곳
- FE: Result. js (게임 결과 화면)

## 🔎 발견한 이슈
점수 표시 글자 겹침 & 닉네임 표기가 탈출함

## 📝 재현 스텝
1. 닉네임을 길게 설정
2. 낮은 점수로 챌린지 완료
3. 결과 화면 확인

## 📌 발생 환경
- PC
- 화면 해상도: Sasumg Galaxy S8 + (360x740)
- 개발자용 크롬

## 🔗 예상 영향
- 정확한 점수 확인 불가
- 미관상 보기 안 좋음

### 스크린샷
<img width="352" alt="Screenshot 2024-05-16 at 8 03 12 PM" src="https://github.com/TeamMoHead/ModuGisang/assets/154266737/861a71b2-eb7c-4308-addc-be5772c9cb5f">

**Comment by pkw-May** [comment]
오마이갓...!!! 잘 맞춘줄 알았는데 아니엇네요 호우..ㅠ
