### ISSUE TITLE
InGame - model warming : Holistic Model 로딩 중에 튕김 현상

### ISSUE THREAD

**Issue by pkw-May** [TeamMoHead/ModuGisang#132]
## #️⃣ 발생한 곳
- InGame 페이지의 loadModel Mode.  LoadModel.js 중 holistic Model 로딩중

## 🔎 발견한 이슈
- 두번째 모델 로딩중에 영상&음성 권한 요청하는 팝업 뜨면서, 화면이 하얘짐
- 어떨 때는 하얀 화면에서 다시 저절로 loadModel Mode로 돌아와서 다시 로딩이 정상적으로 진행되고,
- 어떨 때는 아예 하얀 화면에서 계속 멈춰있음

## 📝 재현 스텝
- 재현은 다시 해봐야 앎...

## 📌 발생 환경
- Mobile
- iPhone 14
- Chrome, PWA(safari)

## 🔗 예상 영향
- 시연 시 치명적 문제...

**Comment by ifindary** [comment]
이슈 발생 이후 코드가 상당수 바뀌었고, 현재 재현이 되지 않으므로 close 처리합니다. 재발생 시 재현 스텝 확인 후 이슈 재등록 부탁드립니다!
